### ISSUE TITLE
Question: Any plan of adding support a different cache strategy for Collection type attribute.

### ISSUE THREAD

**Issue by itopol** [sixhours-team/memcached-spring-boot#48]
For example, I have the next method

`public Collection<Entity> getEntities(Collection<Long> ids)`

I would like to have the ability to save each pair <id, entity> separately in the cache.
I know that Spring cache abstraction is not supported such behavior, but maybe you plan to extend your implementation with such feature?

**Comment by igorbolic** [comment]
This is something we might include in the next major release. There are couple of things to be done before adding this functionality.

**Comment by sasabolic** [comment]
@itopol Hi, I know it past a long time since this issue was opened. But I don't think there's a need for such extension. Firstly, we have to follow Spring's Cashing contract in order to support cache implementations other than Memcached.

And with a help of `CacheManager` you can get this kind of functionality e.g.:

    @Override
	public List<Book> findAllByIds(Collection<Integer> ids) {
		return ids.stream().map(this::findById).collect(Collectors.toList());
	}

	@Override
	public Book findById(Integer id) {
		Cache booksCache = cacheManager.getCache("books");

		Cache.ValueWrapper valueWrapper = booksCache.get(id);
		if (valueWrapper != null) {
			return (Book) valueWrapper.get();
		}

		Book book = repository.findById(id);
		booksCache.put(id, book);

		return book;
	}

Maybe another solution would be to use self-autowiring where you could use something like this:

    @Resource
	private BookService self;

    @Override
	public List<Book> findAllByIds(Collection<Integer> ids) {
		return ids.stream().map(self::findById).collect(Collectors.toList());
	}

	@Override
	@Cacheable("books")
	public Book findById(Integer id) {
		return repository.findById(id);
	}
