### ISSUE TITLE
keytransformation not working as planned

### ISSUE THREAD

**Issue by davidkarlsen** [sixhours-team/memcached-spring-boot#95]
https://github.com/sixhours-team/memcached-spring-boot/blob/master/memcached-spring-boot-autoconfigure/src/main/java/io/sixhours/memcached/cache/MemcachedCache.java#L175
strips whitespace - but still I get the error as described in: https://github.com/killme2008/xmemcached/issues/109
I wonder if the regex is a bit too simple:
https://stackoverflow.com/questions/15625629/regex-expressions-in-java-s-vs-s
another solution would be to define the transformation as an function interface so users can plugin whatever they want, with a default of (fixed) whitespace stripping.
One option - although a bit "hard" would be to plug in a hashing algo, like md5, sha2, sha1 etc.

**Comment by davidkarlsen** [comment]
Ah - hang on, I think maybe only bits of this library is in use (I think they have a non-boot app) - I'll check a bit more and get back - but a pluggable option would be nice anyway I think.

**Comment by igorbolic** [comment]
At a first glance, looks at the XMemcached implementation, perhaps switching to binary protocol could remedy the issue with key validation: `memcached.cache.protocol: binary`

**Comment by davidkarlsen** [comment]
Yes, that would be the 1st choice, unfortunately not possible due to: https://github.com/facebook/mcrouter/issues/6

**Comment by igorbolic** [comment]
@davidkarlsen I made some more look into the issue, it appears that the value you are trying to add for the key `[1234, 00123456789]` is done directly though XMemcached client, instead of through [MemcachedCache](https://github.com/sixhours-team/memcached-spring-boot/blob/master/memcached-spring-boot-autoconfigure/src/main/java/io/sixhours/memcached/cache/MemcachedCache.java).

If you take a look at the implementation, we are prepending the key with app prefix & namespace value. So the actual key sent to XMemcached client would be something like:

`memcached:spring-boot`**:**`test-cache`**:**`1582707685712`**:**`[1234,00123456789]`

where

- `memcached:spring-boot` = cache prefix
- `test-cache` = cache name
- `1582707685712` = namespace value
- `[1234,00123456789]` = key value with whitespaces removed

Can you reproduce the issue using the **mcrouter** with the sample app we have, by hard-coding the example key in [SimpleBookRepository](https://github.com/sixhours-team/spring-boot-memcached-demo-java/blob/master/src/main/java/io/sixhours/memecached/demo/SimpleBookRepository.java) e.g. `@Cacheable(value = "books", key = "[1234, 00123456789]")`?

**Comment by davidkarlsen** [comment]
Yes, I checked back with the team - they aren't using boot - but using the cache-manager manually - so I think we close this.
Sorry about the noise.

**Comment by igorbolic** [comment]
> Yes, I checked back with the team - they aren't using boot - but using the cache-manager manually - so I think we close this.
> Sorry about the noise.

No worries. Thanx for quick reply 👍
